#include <iostream>
using namespace std;

int main() {
  class Caixa{
    int valor;
    bool par;
    Caixa* anter;
  };
  int topo = -1
  int rodadas;
  cin >> rodadas;
  while(rodadas > 0){
        int entrada;
        cin >> entrada;
        while(entrada != 0){
            if (topo = -1){
                Caixa * elemento = new Caixa
            }
            else{
                Caixa * elemento = new Caixa
                *(elemento
            }

        }
  }
  return 0;
}
